version: 4.3.11 / 4.4 RC 1 / 5.0 beta (.NET core & netstandard)
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from
  
