version: 4.4.12 / 4.5 beta (structured logging + .NET Standard 2)
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from
  
