version: 4.4.13 / 4.5 rc (structured logging + .NET Standard 1 + .NET Standard 2 + more)
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from
  
