news:
 # enabled: true
 # text: NLog 4.7 has been released!
  readmore_text: See new post
  readmore_link: https://nlog-project.org/2020/03/28/nlog-4-7-has-been-released.html
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from
  
